[tool.poetry]
package-mode = false
name = "asyncFastApiStore"
version = "0.1.0"
description = "Simple Demo of FastApi"


[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = "^0.31.0"
pydantic-settings = "^2.5.2"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.35" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
